import {
  AbstractControl,
  FormBuilder,
  ReactiveFormsModule,
  ValidationErrors,
  ValidatorFn,
  Validators,
} from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { TranslatePipe } from '@ngx-translate/core';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { MessageModule } from 'primeng/message';
import { PasswordModule } from 'primeng/password';
import { finalize } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';

/**
 * `/auth/reset-password?token=…&email=…` (M5 PR-A). The `token` + `email`
 * are picked from the URL — they're embedded in the email link
 * generated by `ResetPassword::createUrlUsing()` in the server's
 * `AppServiceProvider`. The user supplies a new password (with
 * confirmation); on success they're redirected to login with a
 * one-shot success state.
 *
 * **Failure UX.** The server collapses every reset-side failure
 * (invalid token, expired token, unknown email, mismatched
 * confirmation, weak password) to a 422 with an `errors.email`
 * message. We render a single "the link is invalid or has expired"
 * panel and offer a "Request a new link" CTA — no attempt to
 * differentiate the underlying cause.
 *
 * **Missing token guard.** Visiting `/auth/reset-password` with no
 * token shows the same invalid-link error so a user who pasted half
 * the URL doesn't sit on an empty form.
 */
@Component({
  selector: 'app-reset-password',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    RouterLink,
    ButtonModule,
    InputTextModule,
    MessageModule,
    PasswordModule,
    TranslatePipe,
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
  templateUrl: './reset-password.component.html',
  styleUrl: './reset-password.component.scss',
})
export class ResetPasswordComponent {
  private readonly fb = inject(FormBuilder);
  private readonly auth = inject(AuthService);
  private readonly route = inject(ActivatedRoute);
  private readonly router = inject(Router);

  readonly loading = signal(false);
  readonly success = signal(false);
  readonly tokenInvalid = signal(false);

  private readonly token: string;
  private readonly email: string;

  readonly form = this.fb.group(
    {
      password: ['', [Validators.required, Validators.minLength(8)]],
      passwordConfirmation: ['', Validators.required],
    },
    { validators: passwordsMatchValidator() },
  );

  constructor() {
    const params = this.route.snapshot.queryParamMap;
    this.token = params.get('token') ?? '';
    this.email = params.get('email') ?? '';

    // No token in the URL = the user didn't get here from a real email
    // link. Surface the invalid-link panel up-front rather than make
    // them fill in the form for nothing.
    if (this.token === '' || this.email === '') {
      this.tokenInvalid.set(true);
    }
  }

  submit(): void {
    if (this.tokenInvalid() || this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    this.loading.set(true);

    this.auth
      .resetPassword({
        email: this.email,
        token: this.token,
        password: this.form.value.password ?? '',
        password_confirmation: this.form.value.passwordConfirmation ?? '',
      })
      .pipe(finalize(() => this.loading.set(false)))
      .subscribe({
        next: () => {
          this.success.set(true);
          // Auto-redirect to login after a short pause so the user
          // can read the success message; navigation lands on the
          // login form pre-filled with their email so they re-auth in
          // one click.
          setTimeout(
            () => this.router.navigate(['/auth/login'], { queryParams: { email: this.email } }),
            1500,
          );
        },
        error: () => {
          // Server collapses every reset-side failure to 422; we don't
          // try to differentiate the cause here.
          this.tokenInvalid.set(true);
        },
      });
  }

  get password() {
    return this.form.get('password')!;
  }

  get passwordConfirmation() {
    return this.form.get('passwordConfirmation')!;
  }
}

/**
 * Cross-field validator: passwordConfirmation must match password.
 * Surfaces as `passwordsMismatch` on the FORM so the template can
 * render the error under the confirmation field without coupling the
 * confirmation control's own `errors` object to the other field's value.
 */
function passwordsMatchValidator(): ValidatorFn {
  return (group: AbstractControl): ValidationErrors | null => {
    const pw = group.get('password')?.value;
    const conf = group.get('passwordConfirmation')?.value;
    if (pw && conf && pw !== conf) {
      return { passwordsMismatch: true };
    }
    return null;
  };
}
