#!/usr/bin/env node
/**
 * Pre-build hook: derive the current app version from git and write it into
 * `src/environments/version.ts` so the sidebar footer (#160) renders the
 * actual tag the bundle was cut from.
 *
 * Run automatically by the `prebuild` npm script. Falls back to "dev" if
 * git is unreachable (no .git directory, shallow clone without tags, etc.) —
 * doesn't fail the build.
 */
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const OUT_PATH = path.resolve(__dirname, '..', 'src', 'environments', 'version.ts');

// `git describe --tags --always` produces three shapes:
//   - "v1.2.0"             on a tagged commit (clean release)
//   - "v1.2.0-3-gabc1234"  N commits ahead of the tag, abbreviated SHA
//   - "abc1234"            no tags reachable — only the bare SHA
//
// We only need the network (a `git fetch`) to recover the first two
// shapes from the third — i.e. when the local clone has no tags. Local
// dev builds and tag-aware CI runners both produce the first two
// shapes on the FIRST describe call, so they pay zero network cost.
const SHA_ONLY = /^[0-9a-f]{7,40}$/;

function tryDescribe() {
  try {
    // `stdio: [ignore, pipe, ignore]` silences stderr without a shell
    // redirection, so the script works on Windows / cmd shells too where
    // `2>/dev/null` is meaningless. A missing .git or git binary throws
    // and the caller falls through to the `dev` default.
    return execSync('git describe --tags --always', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return null;
  }
}

function resolveVersion() {
  // 1. First describe attempt — local dev builds and tag-aware CI hit
  //    this branch and exit immediately. No `git fetch`, no network,
  //    no extra latency on every `npm run build`.
  let raw = tryDescribe();

  // 2. Bare-SHA result OR describe failed: best-effort `git fetch
  //    --tags` and re-describe. Cloudflare Pages (and most CI defaults)
  //    ship a shallow clone with no tags, which falls into this branch.
  //    Stdout is fully ignored — we only care that the fetch updates
  //    the local tag refs, not its output.
  if (!raw || SHA_ONLY.test(raw)) {
    try {
      execSync('git fetch --tags --quiet', {
        stdio: ['ignore', 'ignore', 'ignore'],
      });
      const refetched = tryDescribe();
      if (refetched) {
        raw = refetched;
      }
    } catch {
      // No remote access (offline build, auth prompt, no remote at all)
      // — proceed with whatever the first describe produced.
    }
  }

  if (!raw) return 'dev';

  // Bare-SHA fallback (shallow clone with no remote / no tags ever
  // pushed). Prefix with `dev-` so the sidebar footer at least reads as
  // "untagged dev build at commit 42f69e" instead of an unexplained
  // hex string. The tagged + ahead-of-tag shapes already carry the
  // semantic version up front, so they pass through as-is.
  if (SHA_ONLY.test(raw)) {
    return `dev-${raw}`;
  }
  return raw;
}

function main() {
  const tag = resolveVersion();
  const contents = `/**
 * Build-time app version, surfaced quietly in the sidebar footer (#160).
 *
 * AUTOGENERATED by scripts/write-version.cjs — do not commit changes here.
 * The committed default value is \`dev\`; this file is regenerated on every
 * \`ng build\` (CI runs the prebuild script before each Pages deploy).
 */
export const VERSION = {
  /** Resolved from \`git describe --tags --always\` at build time. */
  tag: ${JSON.stringify(tag)},
} as const;
`;
  fs.writeFileSync(OUT_PATH, contents, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[write-version] ${tag} → ${path.relative(path.resolve(__dirname, '..'), OUT_PATH)}`);
}

main();
