#!/usr/bin/env node
/**
 * Pre-build hook: derive the current app version from git and write it into
 * `src/environments/version.ts` so the sidebar footer (#160) renders the
 * actual tag the bundle was cut from.
 *
 * Run automatically by the `prebuild` npm script. Falls back to "dev" if
 * git is unreachable (no .git directory, shallow clone without tags, etc.) —
 * doesn't fail the build.
 */
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const OUT_PATH = path.resolve(__dirname, '..', 'src', 'environments', 'version.ts');

function resolveVersion() {
  // Best-effort tag fetch BEFORE describe. Cloudflare Pages (and most CI
  // defaults) does a shallow clone with no tags, so `git describe --tags`
  // can't reach the semantic-release tag and falls back to the bare
  // commit SHA — the sidebar footer ends up rendering "42f69e" instead
  // of "v1.2.0", which is gibberish to the user. Fetching tags
  // explicitly is the canonical fix.
  //
  // Failure is swallowed (no remote access, offline build, no .git): we
  // proceed with whatever local refs are available and let the SHA-only
  // fallback below format something legible.
  try {
    execSync('git fetch --tags --quiet', {
      stdio: ['ignore', 'pipe', 'ignore'],
    });
  } catch {
    // best-effort — proceed
  }

  try {
    // `stdio: [ignore, pipe, ignore]` silences stderr without a shell
    // redirection, so the script works on Windows / cmd shells too where
    // `2>/dev/null` is meaningless. A missing .git or git binary throws
    // and we fall through to the catch with the `dev` default.
    const raw = execSync('git describe --tags --always', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();

    if (!raw) return 'dev';

    // `git describe --tags --always` produces three shapes:
    //   - "v1.2.0"             on a tagged commit (clean release)
    //   - "v1.2.0-3-gabc1234"  N commits ahead of the tag, abbreviated SHA
    //   - "abc1234"            no tags reachable — only the bare SHA
    //
    // The bare-SHA form reads as gibberish in the sidebar ("42f69e" tells
    // the user nothing about the build). Re-format it with a `dev-`
    // prefix so the version line at least communicates "untagged dev
    // build at commit 42f69e". The tagged + ahead-of-tag forms already
    // carry the semantic version up front, so they pass through as-is.
    if (/^[0-9a-f]{7,40}$/.test(raw)) {
      return `dev-${raw}`;
    }
    return raw;
  } catch {
    // Outside a git checkout (e.g. some Docker build stages) — leave the
    // default committed value alone rather than emit a bogus tag.
    return 'dev';
  }
}

function main() {
  const tag = resolveVersion();
  const contents = `/**
 * Build-time app version, surfaced quietly in the sidebar footer (#160).
 *
 * AUTOGENERATED by scripts/write-version.cjs — do not commit changes here.
 * The committed default value is \`dev\`; this file is regenerated on every
 * \`ng build\` (CI runs the prebuild script before each Pages deploy).
 */
export const VERSION = {
  /** Resolved from \`git describe --tags --always\` at build time. */
  tag: ${JSON.stringify(tag)},
} as const;
`;
  fs.writeFileSync(OUT_PATH, contents, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[write-version] ${tag} → ${path.relative(path.resolve(__dirname, '..'), OUT_PATH)}`);
}

main();
