#!/usr/bin/env node
/**
 * Pre-build hook: derive the current app version from git and write it into
 * `src/environments/version.ts` so the sidebar footer (#160) renders the
 * actual tag the bundle was cut from.
 *
 * Run automatically by the `prebuild` npm script. Falls back to "dev" if
 * git is unreachable (no .git directory, shallow clone without tags, etc.) —
 * doesn't fail the build.
 */
const { execSync } = require('node:child_process');
const fs = require('node:fs');
const path = require('node:path');

const OUT_PATH = path.resolve(__dirname, '..', 'src', 'environments', 'version.ts');

function resolveVersion() {
  try {
    // `stdio: [ignore, pipe, ignore]` silences stderr without a shell
    // redirection, so the script works on Windows / cmd shells too where
    // `2>/dev/null` is meaningless. A missing .git or git binary throws
    // and we fall through to the catch with the `dev` default.
    const tag = execSync('git describe --tags --always', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
    return tag || 'dev';
  } catch {
    // Outside a git checkout (e.g. some Docker build stages) — leave the
    // default committed value alone rather than emit a bogus tag.
    return 'dev';
  }
}

function main() {
  const tag = resolveVersion();
  const contents = `/**
 * Build-time app version, surfaced quietly in the sidebar footer (#160).
 *
 * AUTOGENERATED by scripts/write-version.cjs — do not commit changes here.
 * The committed default value is \`dev\`; this file is regenerated on every
 * \`ng build\` (CI runs the prebuild script before each Pages deploy).
 */
export const VERSION = {
  /** Resolved from \`git describe --tags --always\` at build time. */
  tag: ${JSON.stringify(tag)},
} as const;
`;
  fs.writeFileSync(OUT_PATH, contents, 'utf8');
  // eslint-disable-next-line no-console
  console.log(`[write-version] ${tag} → ${path.relative(path.resolve(__dirname, '..'), OUT_PATH)}`);
}

main();
