<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * `community_posts` (#600, M9 community layer). Parent table for the
 * community feed inside the athlete portal. Three first-class post
 * types (see `App\Enums\CommunityPostType`):
 *
 * - `belt_promotion` — auto-generated by an Observer on `athletes.belt`
 *   change (PR-B).
 * - `event` — owner-created event post with date + location (PR-E).
 * - `owner_announcement` — reserved enum slot for V1 follow-up / V2.
 *
 * V2-forward: `visibility` already supports `'public'` for the
 * cross-academy + mappa feature; V1 always inserts `'academy'`.
 *
 * The shape of `payload` varies by `type` — see the PRD at
 * `docs/specs/m9-community.md` § Tech decisions for the per-type
 * shapes. Casted as `array` on the Eloquent model.
 */
return new class () extends Migration {
    public function up(): void
    {
        Schema::create('community_posts', function (Blueprint $table): void {
            $table->id();

            // Single-academy scope (V1 hard rule). Cascade on academy
            // deletion: if an academy is hard-deleted (the post-contract
            // 30-day purge path), its community posts go with it.
            $table->foreignId('academy_id')
                ->constrained('academies')
                ->cascadeOnDelete();

            // Discriminator for the payload shape. Stored as string so
            // it's SQLite-portable for PEST in-memory tests; enum
            // validation lives in the Eloquent cast +
            // FormRequest layer.
            $table->string('type', 32);

            // Audience. Default 'academy' (V1). 'public' is reserved
            // for V2 cross-academy without requiring a migration.
            $table->string('visibility', 32)->default('academy');

            // Type-specific payload — see PRD § Tech decisions.
            // SQLite stores this as TEXT under the hood; the Laravel
            // `array` cast on the model handles JSON encode/decode on
            // both drivers.
            $table->json('payload');

            // Who authored the post. For `belt_promotion`, this is the
            // owner who triggered the belt change (the system observer
            // captures their id from the request context). For `event`
            // it's the owner who created the event. For potential
            // future `owner_announcement` it'll be the owner.
            // Cascade: hard-deleting the user nukes their posts.
            $table->foreignId('created_by_user_id')
                ->constrained('users')
                ->cascadeOnDelete();

            $table->timestamps();
            $table->softDeletes();

            // The feed query is `WHERE academy_id = ? AND deleted_at IS
            // NULL ORDER BY created_at DESC LIMIT 20` paginated. This
            // index covers all three predicates in order, so the
            // feed-page roundtrip stays index-only on the parent table.
            $table->index(['academy_id', 'deleted_at', 'created_at']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('community_posts');
    }
};
