#!/usr/bin/env bash
#
# clean.sh — remove build OUTPUT. Nothing else.
#
# Usage:
#   ./clean.sh              # everything below
#   ./clean.sh desktop      # desktop/dist + desktop/release
#   ./clean.sh client       # client/dist
#
# Removes, because these are regenerated by a build and nothing else reads them:
#   desktop/dist      compiled main + preload + the copied renderer
#   desktop/release   electron-builder's installers
#   client/dist       ng build output
#
# Deliberately does NOT remove, because each has a different cost and bundling
# them into one command is how `clean` becomes something nobody dares run:
#   client/.angular         ng's build cache — dropping it buys tidiness and
#                           costs a slow rebuild. Different trade, own target
#                           if it ever earns one.
#   node_modules, vendor    the "something is corrupt, reset it" case. Recovery
#   desktop/runtime/php     is npm ci + composer install + a verified 30 MB
#                           download. Needs an explicitly-named target, never a
#                           `clean` alias.
#   cypress screenshots     transient and gitignored, but tiny.
#
# The desktop half delegates to `desktop/scripts/clean.mjs` rather than
# repeating the paths — that script is also what `npm run dist` runs, and two
# lists of directories to delete is exactly how one of them goes stale.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Reports its own size, so a `clean` never removes something silently.
remove() {
  local target="$1"
  local label="$2"

  if [ ! -e "$target" ]; then
    return 0
  fi

  local size
  size="$(du -sh "$target" 2>/dev/null | cut -f1)"
  rm -rf "$target"
  echo "removed $label ($size)"
}

clean_desktop() {
  echo "── desktop ──"
  ( cd "$ROOT/desktop" && node scripts/clean.mjs )
}

# `client/dist` is written by `ng build` INSIDE the client container, which runs
# as root. On Linux the ./client bind mount is the host's real filesystem, so
# those files really are root-owned and a plain `rm -rf` from the host fails
# per-file with EACCES — half-deleting the tree and leaving a directory that
# still looks like a build. (On Windows the 9p share fakes ownership and the
# host rm works, which is why this needs a fallback and not a hard requirement.)
#
# So: try the host first, and if anything survives, delete it from a throwaway
# container that IS root. `docker run` rather than `docker exec` so this works
# whether or not the dev stack happens to be up.
clean_client() {
  echo "── client ──"

  if [ ! -e "$ROOT/client/dist" ]; then
    echo "client: nothing to remove"
    return 0
  fi

  local size
  size="$(du -sh "$ROOT/client/dist" 2>/dev/null | cut -f1)"
  rm -rf "$ROOT/client/dist" 2>/dev/null || true

  if [ -e "$ROOT/client/dist" ]; then
    echo "client/dist is not ours — removing it from a container"
    docker run --rm -v "$ROOT/client":/mnt alpine:3 rm -rf /mnt/dist
  fi

  if [ -e "$ROOT/client/dist" ]; then
    echo "could not remove client/dist — is docker running?" >&2
    return 1
  fi

  echo "removed client/dist ($size)"
}

case "${1:-all}" in
  all)     clean_desktop && clean_client ;;
  desktop) clean_desktop ;;
  client)  clean_client ;;
  *)
    echo "usage: $0 [all|desktop|client]" >&2
    exit 2
    ;;
esac
