<?php

declare(strict_types=1);

return [
    'academy' => [
        'name' => 'Sample Academy',
        // Structured address (#72) — optional, can be `null` to skip seeding
        // an address. The shape mirrors the API contract one-for-one so the
        // seeder passes the array straight to `SyncAddressAction`.
        'address' => [
            'line1' => '123 Sample Street',
            'line2' => null,
            'city' => 'Sample City',
            'postal_code' => '00100',
            'province' => 'RM',
            'country' => 'IT',
        ],
    ],
    'athletes' => [
        [
            'first_name' => 'Owner',
            'last_name' => 'One',
            'email' => 'owner.one@example.test',
            'date_of_birth' => '1990-01-15',
            'belt' => 'black',
            'stripes' => 0,
            'joined_at' => '2023-03-01',
            'attendance_probability' => 1.0,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Two',
            'email' => null,
            'date_of_birth' => '1982-04-10',
            'belt' => 'white',
            'stripes' => 4,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Three',
            'email' => null,
            'date_of_birth' => null,
            'belt' => 'blue',
            'stripes' => 1,
            'joined_at' => '2023-03-01',
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Four',
            'email' => null,
            'date_of_birth' => '1990-06-20',
            'belt' => 'blue',
            'stripes' => 0,
            'joined_at' => '2023-03-01',
            'attendance_probability' => 0.9,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Five',
            'email' => null,
            'date_of_birth' => '2007-09-10',
            'belt' => 'blue',
            'stripes' => 0,
            'joined_at' => null,
            'attendance_probability' => 0.95,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Six',
            'email' => null,
            'date_of_birth' => '2009-12-15',
            'belt' => 'white',
            'stripes' => 2,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Seven',
            'email' => null,
            'date_of_birth' => null,
            'belt' => 'brown',
            'stripes' => 0,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Eight',
            'email' => null,
            'date_of_birth' => '1994-11-02',
            'belt' => 'blue',
            'stripes' => 0,
            'joined_at' => '2023-03-01',
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Nine',
            'email' => null,
            'date_of_birth' => '1994-04-11',
            'belt' => 'white',
            'stripes' => 0,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Ten',
            'email' => null,
            'date_of_birth' => '2003-04-29',
            'belt' => 'white',
            'stripes' => 0,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Eleven',
            'email' => null,
            'date_of_birth' => '2004-10-31',
            'belt' => 'white',
            'stripes' => 0,
            'joined_at' => '2023-03-01',
            'attendance_probability' => null,
        ],
        [
            'first_name' => 'Athlete',
            'last_name' => 'Twelve',
            'email' => null,
            'date_of_birth' => '1985-12-26',
            'belt' => 'white',
            'stripes' => 0,
            'joined_at' => null,
            'attendance_probability' => null,
        ],
    ],
    'attendance' => [
        'training_days_of_week' => [2, 4, 6],
        'simulation_window_days' => 365,
        'default_probability' => 0.6,
    ],
];
