import { describe, expect, it } from 'vitest';

import {
  buildAuthorizeUrl,
  createPkcePair,
  needsRefresh,
  parseCallbackUrl,
  DRIVE_SCOPE,
} from './drive-auth.js';

/**
 * The pure half of the Google OAuth flow (#1301): what URL to open, what came
 * back, and whether the access token is still good. No sockets, no clock, no
 * Electron — everything that decides something lives here so it can be tested,
 * and `drive-io.ts` is left with nothing but the I/O.
 */

describe('createPkcePair', () => {
  // A desktop app cannot keep a client secret — the binary is on the user's
  // disk. PKCE is what makes the flow safe anyway: the code is useless without
  // the verifier, which never leaves this process.
  //
  // Checked against RFC 7636 Appendix B rather than against our own output:
  // a vector generated by the implementation would pass no matter what the
  // implementation did.
  it('matches the RFC 7636 Appendix B challenge vector', () => {
    const rfcVerifier = 'dBjftJeZ4CVP-mB92K27uhbUJU1p1r_wW1gFWFOEjXk';
    const rfcChallenge = 'E9Melhoa2OwvFrEMTJguCHaoeK1t8URWbuGJSstw-cM';

    // The pair derives the challenge from the verifier it just made, so feed
    // the RFC's verifier in by making `random` produce exactly its bytes.
    const pair = createPkcePair(() => Buffer.from(rfcVerifier, 'base64url'));

    expect(pair.verifier).toBe(rfcVerifier);
    expect(pair.challenge).toBe(rfcChallenge);
  });

  it('emits base64url, never standard base64', () => {
    const pair = createPkcePair(() => Buffer.alloc(32, 251));

    for (const value of [pair.verifier, pair.challenge]) {
      expect(value).not.toContain('=');
      expect(value).not.toContain('+');
      expect(value).not.toContain('/');
    }
  });

  it('produces a verifier inside the RFC 7636 length bounds', () => {
    const pair = createPkcePair();

    expect(pair.verifier.length).toBeGreaterThanOrEqual(43);
    expect(pair.verifier.length).toBeLessThanOrEqual(128);
    expect(pair.verifier).toMatch(/^[A-Za-z0-9\-._~]+$/);
  });

  it('never repeats a verifier', () => {
    const seen = new Set(Array.from({ length: 50 }, () => createPkcePair().verifier));

    expect(seen.size).toBe(50);
  });
});

describe('buildAuthorizeUrl', () => {
  const base = {
    clientId: 'client-123.apps.googleusercontent.com',
    redirectUri: 'http://127.0.0.1:51789/callback',
    challenge: 'CHALLENGE',
    state: 'STATE',
  };

  it('asks only for the narrow drive.file scope', () => {
    const url = new URL(buildAuthorizeUrl(base));

    // drive.file grants access ONLY to files this app created. The broad
    // `drive` scope would read the user's whole Drive, is classed sensitive,
    // and would drag the app into Google's verification review. Never widen
    // this without understanding both consequences.
    expect(url.searchParams.get('scope')).toBe(DRIVE_SCOPE);
    expect(DRIVE_SCOPE).toBe('https://www.googleapis.com/auth/drive.file');
  });

  it('requests an offline authorization code with S256', () => {
    const url = new URL(buildAuthorizeUrl(base));

    expect(url.origin + url.pathname).toBe('https://accounts.google.com/o/oauth2/v2/auth');
    expect(url.searchParams.get('response_type')).toBe('code');
    expect(url.searchParams.get('code_challenge_method')).toBe('S256');
    expect(url.searchParams.get('code_challenge')).toBe('CHALLENGE');
    // Without offline access Google returns no refresh token, and the sync
    // would silently stop working the first time the access token expired.
    expect(url.searchParams.get('access_type')).toBe('offline');
    expect(url.searchParams.get('state')).toBe('STATE');
    expect(url.searchParams.get('redirect_uri')).toBe(base.redirectUri);
  });

  it('forces the consent screen so a re-link always returns a refresh token', () => {
    // Google omits the refresh token on a repeat authorization unless prompted.
    // Re-linking after a revoke would otherwise appear to succeed and then fail
    // an hour later.
    expect(new URL(buildAuthorizeUrl(base)).searchParams.get('prompt')).toBe('consent');
  });
});

describe('parseCallbackUrl', () => {
  const state = 'THE-STATE';

  it('reads the code when the state matches', () => {
    const result = parseCallbackUrl('/callback?code=abc123&state=THE-STATE', state);

    expect(result).toEqual({ ok: true, code: 'abc123' });
  });

  // The state check is the CSRF defence for the loopback redirect: anything on
  // the machine can hit 127.0.0.1 while the server is listening.
  it('refuses a mismatched state', () => {
    const result = parseCallbackUrl('/callback?code=abc123&state=SOMEONE-ELSE', state);

    expect(result).toEqual({ ok: false, reason: 'state_mismatch' });
  });

  it('refuses a missing state', () => {
    expect(parseCallbackUrl('/callback?code=abc123', state)).toEqual({
      ok: false,
      reason: 'state_mismatch',
    });
  });

  it('surfaces the error Google sent instead of inventing one', () => {
    const result = parseCallbackUrl('/callback?error=access_denied&state=THE-STATE', state);

    expect(result).toEqual({ ok: false, reason: 'access_denied' });
  });

  it('refuses a callback with neither code nor error', () => {
    expect(parseCallbackUrl('/callback?state=THE-STATE', state)).toEqual({
      ok: false,
      reason: 'no_code',
    });
  });

  it('ignores a request to any other path', () => {
    expect(parseCallbackUrl('/favicon.ico', state)).toEqual({ ok: false, reason: 'not_callback' });
  });
});

describe('needsRefresh', () => {
  const now = 1_700_000_000_000;

  it('is false while the token has comfortable life left', () => {
    expect(needsRefresh({ expiresAt: now + 10 * 60_000 }, now)).toBe(false);
  });

  // Refreshing early costs one cheap call; refreshing late means an upload
  // fails with a 401 that looks like a broken link to the user.
  it('is true inside the skew window, before actual expiry', () => {
    expect(needsRefresh({ expiresAt: now + 30_000 }, now)).toBe(true);
  });

  it('is true once expired', () => {
    expect(needsRefresh({ expiresAt: now - 1 }, now)).toBe(true);
  });

  it('is true when the expiry is unknown, rather than assuming it is valid', () => {
    expect(needsRefresh({ expiresAt: null }, now)).toBe(true);
  });
});
