/**
 * Build-time app version, surfaced quietly in the sidebar footer (#160)
 * and used as the embedded identity for the runtime cache-bust check
 * (#548 — `VersionCheckService` compares `VERSION.sha` against the
 * server-served `/version.json` to detect stuck-on-old-bundle tabs).
 *
 * AUTOGENERATED by scripts/write-version.cjs — do not commit changes
 * here. The committed default values are sentinel `dev` strings so
 * `ng serve` (no prebuild) and a fresh clone both work; this file is
 * regenerated on every `ng build` (CI runs the prebuild script before
 * each Pages deploy).
 *
 * **Typing: explicit `AppVersion` interface with `string` fields**
 * rather than `as const` literal narrowing. `as const` shipped on
 * v2.4.0 and broke the production build (TS2367) the moment the
 * prebuild wrote a real SHA — `VERSION.sha === 'dev'` had no literal-
 * type overlap. The interface is re-emitted into the generated file so
 * downstream code can `import type { AppVersion } from './version'`
 * without a round-trip via a separate types module. See #554 hotfix.
 */
export interface AppVersion {
  /** Resolved from `git describe --tags --always` at build time. */
  readonly tag: string;
  /** Full 40-char commit SHA — used as the cache-bust identity. */
  readonly sha: string;
  /** ISO-8601 UTC build timestamp — diagnostic field, not used as identity. */
  readonly buildTime: string;
}

export const VERSION: AppVersion = {
  tag: "dev",
  sha: "0000000000000000000000000000000000000000",
  buildTime: "2026-05-24T16:44:35.311Z",
};
