<?php

declare(strict_types=1);

namespace App\Support;

use App\Models\User;
use PragmaRX\Google2FA\Google2FA;

/**
 * Thin wrapper over `pragmarx/google2fa` (#412). Centralises every
 * 2FA primitive (generate secret, verify TOTP, generate backup
 * codes, consume a backup code) so callers don't reach into the
 * library directly — easier to swap implementations later (HOTP,
 * WebAuthn) without touching every entry point.
 *
 * **Secret format**: 32-character base32 string (160 bits of
 * entropy, the RFC 6238 recommendation). Generated by
 * `Google2FA::generateSecretKey(32)` which uses
 * `random_bytes`-backed CSPRNG.
 *
 * **Backup codes**: 8 single-use plaintext codes, format
 * `XXXX-XXXX` (8 alphanumeric chars, dashed for readability).
 * Stored as an encrypted JSON array on `users.two_factor_recovery_codes`.
 * Consumed by removing the entry from the array on a successful
 * login-challenge use — the array shortens by one.
 *
 * **TOTP verification window**: default 1 (= ±30s either side of
 * the current time slot) to absorb clock skew between user device
 * and server. Trade-off: a code is reusable within a 90s window.
 * RFC 6238 calls this acceptable for typical use.
 */
final class TwoFactorAuth
{
    public const int RECOVERY_CODE_COUNT = 8;

    public static function generateSecret(): string
    {
        return new Google2FA()->generateSecretKey(32);
    }

    /**
     * Returns the otpauth:// URI suitable for QR-code generation.
     * `issuer` = "Budojo" (the brand the user sees in their
     * authenticator app). `label` = the user's email so the user
     * can distinguish multiple Budojo accounts on the same
     * authenticator.
     */
    public static function provisioningUri(User $user, string $secret): string
    {
        return new Google2FA()->getQRCodeUrl(
            company: 'Budojo',
            holder: $user->email,
            secret: $secret,
        );
    }

    public static function verifyTotp(string $secret, string $code): bool
    {
        // `verifyKey` returns false on malformed input (length, chars)
        // — no need for explicit shape validation upstream. Library
        // signature is `bool|int` (truthy result is the time slot
        // offset); we only care about success/failure, so cast.
        return (bool) new Google2FA()->verifyKey($secret, $code);
    }

    /** @return array<int, string> */
    public static function generateRecoveryCodes(): array
    {
        $codes = [];
        for ($i = 0; $i < self::RECOVERY_CODE_COUNT; $i++) {
            $codes[] = self::generateRecoveryCode();
        }

        return $codes;
    }

    /**
     * Returns the remaining codes after the matched one is removed.
     * Returns `null` when no code in the array matched the input —
     * the caller should treat that as an authentication failure.
     *
     * @param array<int, string> $codes
     * @return array<int, string>|null
     */
    public static function consumeRecoveryCode(array $codes, string $input): ?array
    {
        // Normalize BOTH sides identically so a user typing
        // `aaaa-bbbb`, `AAAABBBB`, or ` aaaa bbbb ` all match a stored
        // `AAAA-BBBB`. Strip every non-alphanumeric char then
        // upper-case — covers dashes, spaces, accidental hyphens and
        // capitalization drift in one pass.
        $needle = self::normalizeCode($input);
        if ($needle === '') {
            return null;
        }
        $remaining = array_values(array_filter(
            $codes,
            fn (string $code): bool => self::normalizeCode($code) !== $needle,
        ));

        return \count($remaining) === \count($codes) ? null : $remaining;
    }

    private static function normalizeCode(string $value): string
    {
        return strtoupper((string) preg_replace('/[^A-Za-z0-9]/', '', $value));
    }

    private static function generateRecoveryCode(): string
    {
        // 8 alphanumeric chars split as XXXX-XXXX for readability.
        // Charset excludes ambiguous chars (0/O, 1/I, etc.) so a
        // user typing a code from a printed backup doesn't fight
        // glyph-similarity issues.
        $alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
        $code = '';
        for ($i = 0; $i < 8; $i++) {
            $code .= $alphabet[random_int(0, \strlen($alphabet) - 1)];
        }

        return substr($code, 0, 4) . '-' . substr($code, 4);
    }
}
