import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { Router } from '@angular/router';
import { TranslatePipe, TranslateService } from '@ngx-translate/core';
import { ConfirmationService, MessageService } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { ToastModule } from 'primeng/toast';
import { TooltipModule } from 'primeng/tooltip';
import { ConfirmDestructiveButtonComponent } from '../../shared/components/confirm-destructive-button/confirm-destructive-button.component';
import { PageHeaderComponent } from '../../shared/components/page-header/page-header.component';
import {
  DesktopBackupService,
  type BackupArchiveView,
} from '../../core/services/desktop-backup.service';

/** An archive row, plus whether it is on this disk and therefore restorable. */
interface BackupRow extends BackupArchiveView {
  local: boolean;
}
import { DesktopKeysService } from '../../core/services/desktop-keys.service';
import {
  BackupFolderService,
  type BackupFolderStateView,
} from '../../core/services/backup-folder.service';
import {
  DriveSyncService,
  type DriveArchiveView,
  type DriveLinkStateView,
} from '../../core/services/drive-sync.service';

/**
 * The error codes with a translation of their own. Anything else falls back to
 * `unknown`, which interpolates the raw code so the thread back to the cause is
 * never lost. Keep in step with `backup.drive.errors` in both i18n files.
 */
/** Same allow-list discipline as the Drive codes: never build a key from a value. */
const KNOWN_FOLDER_ERRORS = new Set(['ENOENT', 'EACCES', 'EPERM', 'ENOSPC', 'EROFS']);

const KNOWN_DRIVE_ERRORS = new Set([
  'invalid_grant',
  'unauthorized',
  'storageQuotaExceeded',
  'network',
  'access_denied',
  'consent_timeout',
  'no_refresh_token',
  'not_configured',
]);

/**
 * `budojo-backup-YYYYMMDD-HHMMSS.zip` -> ISO, for archives that exist only in
 * the Google account and therefore have no local file time (#1301). The name is
 * generated by the main process and is the only timestamp such a row has.
 */
function timestampFromName(name: string): string {
  const match = /(\d{8})-(\d{6})/.exec(name);

  if (match === null) {
    return '';
  }

  const [, date, time] = match;
  const iso = `${date.slice(0, 4)}-${date.slice(4, 6)}-${date.slice(6, 8)}T${time.slice(0, 2)}:${time.slice(2, 4)}:${time.slice(4, 6)}`;

  return new Date(iso).toISOString();
}

/**
 * Data & backup page (#1228). Desktop-only — the route guard redirects on the
 * web, where there is no local database to back up. Shows the last backup, a
 * "Back up now" action, and the archive list with a confirm-gated restore.
 *
 * A backup system nobody can see is a backup system nobody trusts, so the last
 * successful backup is the first thing on the page.
 */
@Component({
  selector: 'app-backup',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    DatePipe,
    TranslatePipe,
    ButtonModule,
    ToastModule,
    TooltipModule,
    ConfirmDestructiveButtonComponent,
    PageHeaderComponent,
  ],
  // ConfirmDestructiveButtonComponent injects ConfirmationService, and
  // app.config.ts deliberately provides only MessageService app-wide — so each
  // host provides this one. Without it every confirm button on the page threw
  // NG0201 and rendered nothing, which meant Restore was missing from the
  // packaged app entirely (#1324). Every other host already did this.
  providers: [ConfirmationService],
  templateUrl: './backup.component.html',
  styleUrl: './backup.component.scss',
})
export class BackupComponent {
  private readonly backup = inject(DesktopBackupService);
  private readonly keys = inject(DesktopKeysService);
  private readonly drive = inject(DriveSyncService);
  private readonly folder = inject(BackupFolderService);
  private readonly messages = inject(MessageService);
  private readonly translate = inject(TranslateService);
  private readonly router = inject(Router);

  protected readonly archives = signal<BackupArchiveView[]>([]);

  /**
   * Google Drive sync (#1301). One list with a location marker rather than two
   * sections: on a fresh machine the local list is empty, and the archives that
   * matter are the ones only the account has.
   */
  protected readonly driveAvailable = this.drive.available;
  protected readonly driveState = signal<DriveLinkStateView>({ configured: false, linked: false });
  protected readonly driveArchives = signal<DriveArchiveView[]>([]);
  protected readonly linking = signal(false);

  /**
   * Backup folder (#1320). The answer to "a backup on this disk does not
   * survive this disk" that needs no account and no API: point at a folder the
   * owner's cloud client already syncs, or a NAS, or a USB stick.
   */
  protected readonly folderAvailable = this.folder.available;
  protected readonly folderState = signal<BackupFolderStateView>({
    folder: null,
    lastCopyAt: null,
    lastError: null,
    lastErrorAt: null,
  });
  protected readonly choosingFolder = signal(false);
  protected readonly copyingToFolder = signal(false);
  protected readonly syncing = signal(false);
  protected readonly loading = signal(true);
  protected readonly backingUp = signal(false);
  protected readonly restoringName = signal<string | null>(null);

  /** Recovery keys (#1254): reveal the code, and paste one to import. */
  protected readonly keysAvailable = this.keys.available;
  protected readonly recoveryCode = signal<string | null>(null);
  protected readonly revealing = signal(false);
  protected readonly importValue = signal('');
  protected readonly importing = signal(false);

  protected readonly lastBackupAt = computed<string | null>(
    () => this.archives()[0]?.createdAt ?? null,
  );

  /**
   * What the list actually renders. Once an account is linked this is the
   * MERGED view, not the local one — on a fresh machine there are no local
   * archives at all, and the ones worth showing are exactly the ones only the
   * account has. Falling back to the local list keeps the page identical for
   * anyone who never connects Drive.
   */
  protected readonly rows = computed<BackupRow[]>(() => {
    if (!this.driveState().linked) {
      return this.archives().map((archive) => ({ ...archive, local: true }));
    }

    return this.driveArchives().map((archive) => ({
      // Restore reads the archive from the LOCAL backups directory, and
      // downloading a remote one is a later slice (#1301). Carrying `local`
      // through is what lets the row refuse instead of spinning forever on a
      // file that is not on this disk.
      local: archive.local,
      name: archive.name,
      // A remote-only archive has no local mtime; its name carries the
      // timestamp, and the row falls back to it rather than showing nothing.
      createdAt: archive.createdAt ?? timestampFromName(archive.name),
      sizeBytes: archive.sizeBytes,
    }));
  });

  constructor() {
    void this.refresh();
  }

  protected async refresh(): Promise<void> {
    this.loading.set(true);
    this.archives.set(await this.backup.list());
    // Dropped before the Drive calls on purpose: the local archives are on this
    // disk and ready, and making the page wait for the network to show them
    // would be slowest exactly when the connection is worst.
    this.loading.set(false);

    // The two destinations are independent: a build with no Drive client still
    // has a backup folder, and gating one on the other is how the folder state
    // silently stopped being read at all.
    if (this.folderAvailable) {
      this.folderState.set(await this.folder.state());
    }

    if (!this.driveAvailable) {
      return;
    }

    this.driveState.set(await this.drive.state());
    // Merged local+remote. The service returns the local half if the remote
    // call fails, so this never blanks the list that always works.
    this.driveArchives.set(await this.drive.archives());
  }

  /** Opens the Google consent screen in the default browser and waits for it. */
  protected async connectDrive(): Promise<void> {
    this.linking.set(true);
    const result = await this.drive.link();
    this.linking.set(false);

    this.messages.add({
      severity: result.ok ? 'success' : 'error',
      summary: this.translate.instant(
        result.ok ? 'backup.drive.connected' : 'backup.drive.connectFailed',
      ),
      detail: result.ok ? (result.account ?? undefined) : result.error,
      life: result.ok ? 4000 : 8000,
    });

    await this.refresh();
  }

  protected async disconnectDrive(): Promise<void> {
    await this.drive.unlink();
    this.messages.add({
      severity: 'success',
      summary: this.translate.instant('backup.drive.disconnected'),
    });
    await this.refresh();
  }

  /**
   * Where an archive currently lives. Icon plus a tooltip and an sr-only label,
   * never colour alone — an icon with no name is unreadable to a screen reader
   * and ambiguous to everyone else.
   */
  protected whereIcon(name: string): string {
    const view = this.driveArchives().find((archive) => archive.name === name);

    if (view?.remote === true) {
      return view.local ? 'pi pi-cloud' : 'pi pi-cloud-download';
    }

    return 'pi pi-desktop';
  }

  protected whereTooltip(name: string): string {
    const view = this.driveArchives().find((archive) => archive.name === name);

    if (view?.remote === true) {
      return view.local ? 'backup.drive.where.both' : 'backup.drive.where.cloudOnly';
    }

    return 'backup.drive.where.localOnly';
  }

  /**
   * Turns the stored error code into a sentence.
   *
   * An allow-list, not `'backup.drive.errors.' + code`: building a key from a
   * value is a documented red flag (client/CLAUDE.md), the parity check cannot
   * see such keys, and `drive-io.ts` emits codes well past the ones translated
   * here — `http_403`, `no_upload_session`, `rateLimitExceeded`, anything
   * Google's API passes through. Each of those would render the raw key on the
   * page that is the ONLY surface for a silently-failing feature.
   */
  protected driveErrorMessage(): string {
    const code = this.driveState().lastError;

    if (code === null || code === undefined) {
      return '';
    }

    const known = KNOWN_DRIVE_ERRORS.has(code) ? code : 'unknown';

    return this.translate.instant(`backup.drive.errors.${known}`, { code });
  }

  protected async chooseFolder(): Promise<void> {
    this.choosingFolder.set(true);
    const result = await this.folder.choose();
    this.choosingFolder.set(false);

    // A cancelled picker is not an error and must not produce a toast.
    if (result.ok) {
      this.messages.add({
        severity: 'success',
        summary: this.translate.instant('backup.folder.chosen'),
      });
      await this.refresh();
    }
  }

  protected async clearFolder(): Promise<void> {
    await this.folder.clear();
    this.messages.add({
      severity: 'success',
      summary: this.translate.instant('backup.folder.cleared'),
    });
    await this.refresh();
  }

  protected async copyToFolderNow(): Promise<void> {
    this.copyingToFolder.set(true);
    const result = await this.folder.copyNow();
    this.copyingToFolder.set(false);

    this.messages.add({
      severity: result.error === undefined ? 'success' : 'error',
      summary: this.translate.instant(
        result.error === undefined ? 'backup.folder.copied' : 'backup.folder.copyFailed',
      ),
    });
    await this.refresh();
  }

  protected async openFolder(): Promise<void> {
    await this.folder.openFolder();
  }

  /** Turns the stored errno into a sentence, through an allow-list. */
  protected folderErrorMessage(): string {
    const code = this.folderState().lastError;

    if (code === null) {
      return '';
    }

    const known = KNOWN_FOLDER_ERRORS.has(code) ? code : 'unknown';

    return this.translate.instant(`backup.folder.errors.${known}`, { code });
  }

  /** The automatic sync already follows every backup; this is for impatience. */
  protected async syncDriveNow(): Promise<void> {
    this.syncing.set(true);
    const result = await this.drive.syncNow();
    this.syncing.set(false);

    this.messages.add({
      severity: result.error === undefined ? 'success' : 'error',
      summary: this.translate.instant(
        result.error === undefined ? 'backup.drive.synced' : 'backup.drive.syncFailed',
      ),
    });

    await this.refresh();
  }

  protected async backupNow(): Promise<void> {
    this.backingUp.set(true);
    const ok = await this.backup.backupNow();
    this.backingUp.set(false);

    this.messages.add({
      severity: ok ? 'success' : 'error',
      summary: this.translate.instant(ok ? 'backup.toast.created' : 'backup.toast.failed'),
    });

    if (ok) {
      await this.refresh();
    }
  }

  protected async restore(archive: BackupArchiveView): Promise<void> {
    this.restoringName.set(archive.name);
    const result = await this.backup.restore(archive.name);
    this.restoringName.set(null);

    if (result.ok) {
      // The main process reloads the window onto the restored data; this toast
      // may not survive that, which is fine — the reload is the confirmation.
      this.messages.add({
        severity: 'success',
        summary: this.translate.instant('backup.toast.restored'),
      });
    } else {
      this.messages.add({
        severity: 'error',
        summary: this.translate.instant('backup.toast.restoreRefused'),
        detail: result.reason,
        life: 8000,
      });
    }
  }

  protected async reveal(): Promise<void> {
    this.revealing.set(true);
    const result = await this.keys.reveal();
    this.revealing.set(false);

    if (result.ok && result.code) {
      this.recoveryCode.set(result.code);
    } else {
      this.messages.add({
        severity: 'error',
        summary: this.translate.instant('backup.keys.revealFailed'),
        detail: result.reason,
        life: 8000,
      });
    }
  }

  protected hideCode(): void {
    this.recoveryCode.set(null);
  }

  protected async copyCode(): Promise<void> {
    const code = this.recoveryCode();
    if (code === null) {
      return;
    }

    try {
      await navigator.clipboard.writeText(code);
      this.messages.add({
        severity: 'success',
        summary: this.translate.instant('backup.keys.copied'),
      });
    } catch {
      // Clipboard can be blocked; the code is on screen to copy by hand.
      this.messages.add({
        severity: 'info',
        summary: this.translate.instant('backup.keys.copyManual'),
      });
    }
  }

  protected setImportValue(value: string): void {
    this.importValue.set(value);
  }

  protected async importKeys(): Promise<void> {
    const code = this.importValue().trim();
    if (code.length === 0) {
      return;
    }

    this.importing.set(true);
    const result = await this.keys.importCode(code);

    if (result.ok) {
      // On success the main process relaunches the app under the new keys, so
      // keep the control disabled — the restart is the confirmation.
      this.messages.add({
        severity: 'success',
        summary: this.translate.instant('backup.keys.importOk'),
        detail: this.translate.instant('backup.keys.importRelaunch'),
      });
    } else {
      this.importing.set(false);
      this.messages.add({
        severity: 'error',
        summary: this.translate.instant('backup.keys.importFailed'),
        detail: result.reason,
        life: 8000,
      });
    }
  }

  protected sizeMb(bytes: number): string {
    return (bytes / (1024 * 1024)).toFixed(1);
  }
}
